export enum FraudType {
  FAST_COMPLETION = 'FAST_COMPLETION',
  GPS_MISMATCH = 'GPS_MISMATCH',
  IMAGE_REUSE = 'IMAGE_REUSE',
  SUSPICIOUS_PATTERN = 'SUSPICIOUS_PATTERN',
  DUPLICATE_REQUEST = 'DUPLICATE_REQUEST',
}

export enum FraudFlagStatus {
  OPEN = 'OPEN',
  REVIEWED = 'REVIEWED',
  DISMISSED = 'DISMISSED',
  CONFIRMED = 'CONFIRMED',
}
