export enum PaymentStatus {
  PENDING = 'PENDING',
  AWAITING_ADMIN_VERIFICATION = 'AWAITING_ADMIN_VERIFICATION',
  PROVIDER_PENDING = 'PROVIDER_PENDING',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
  FAILED = 'FAILED',
  NOT_REQUIRED = 'NOT_REQUIRED', // For subscription-covered jobs
}
