export enum PaymentMode {
  NONE = 'NONE',
  MANUAL_PROVIDER = 'MANUAL_PROVIDER',
  INTEGRATED_PROVIDER = 'INTEGRATED_PROVIDER',
  CASH = 'CASH',
  WALLET = 'WALLET',
  CASH_ON_FIRST_PICKUP = 'CASH_ON_FIRST_PICKUP',
}
