import { MigrationInterface, QueryRunner } from "typeorm";

export class Init1776963576121 implements MigrationInterface {
    name = 'Init1776963576121'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('HOUSEHOLD', 'COLLECTOR', 'ADMIN')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, "email" character varying(255), "phone" character varying(20) NOT NULL, "password_hash" character varying(255) NOT NULL, "role" "public"."users_role_enum" NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "avatar_url" character varying(500), "latitude" numeric(10,8), "longitude" numeric(11,8), "fcm_token" character varying(500), "refresh_token_hash" character varying(255), "avg_rating" numeric(3,2) NOT NULL DEFAULT '0', "total_completed" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "UQ_a000cca60bcf04454e727699490" UNIQUE ("phone"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a000cca60bcf04454e72769949" ON "users" ("phone") `);
        await queryRunner.query(`CREATE INDEX "IDX_ace513fa30d485cfd25c11a9e4" ON "users" ("role") `);
        await queryRunner.query(`CREATE TYPE "public"."jobs_status_enum" AS ENUM('REQUESTED', 'ASSIGNED', 'IN_PROGRESS', 'COMPLETED', 'VALIDATED', 'RATED', 'CANCELLED', 'DISPUTED')`);
        await queryRunner.query(`CREATE TABLE "jobs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "household_id" uuid NOT NULL, "collector_id" uuid, "status" "public"."jobs_status_enum" NOT NULL DEFAULT 'REQUESTED', "scheduled_date" date NOT NULL, "scheduled_time" character varying(20) NOT NULL, "location_address" character varying(500) NOT NULL, "location_lat" numeric(10,8), "location_lng" numeric(11,8), "notes" text, "assigned_at" TIMESTAMP WITH TIME ZONE, "started_at" TIMESTAMP WITH TIME ZONE, "completed_at" TIMESTAMP WITH TIME ZONE, "validated_at" TIMESTAMP WITH TIME ZONE, "cancelled_at" TIMESTAMP WITH TIME ZONE, "cancellation_reason" text, "assignment_attempts" integer NOT NULL DEFAULT '0', "version" integer NOT NULL DEFAULT '1', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_cf0a6c42b72fcc7f7c237def345" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b51d60266d53e1df466549d98d" ON "jobs" ("household_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_d189aac72bc65e3550769bb734" ON "jobs" ("collector_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_a0c30e3eb9649fe7fbcd336a63" ON "jobs" ("status") `);
        await queryRunner.query(`CREATE TABLE "location_updates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "job_id" uuid NOT NULL, "collector_id" uuid NOT NULL, "latitude" numeric(10,8) NOT NULL, "longitude" numeric(11,8) NOT NULL, "accuracy" numeric(6,2) NOT NULL, "speed" numeric(6,2), "heading" numeric(6,2), "network_type" character varying(10), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_78d25ae7727e1b82de588b77092" UNIQUE ("job_id"), CONSTRAINT "PK_fb8762f200a070d3c0ce2a82c3e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_78d25ae7727e1b82de588b7709" ON "location_updates" ("job_id") `);
        await queryRunner.query(`CREATE TYPE "public"."collector_availability_day_of_week_enum" AS ENUM('MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT', 'SUN')`);
        await queryRunner.query(`CREATE TABLE "collector_availability" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "collector_id" uuid NOT NULL, "day_of_week" "public"."collector_availability_day_of_week_enum" NOT NULL, "start_time" TIME NOT NULL, "end_time" TIME NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "uq_collector_day_slot" UNIQUE ("collector_id", "day_of_week", "start_time"), CONSTRAINT "PK_4f9ddccf307f2b4ae6ece855817" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_06a030107ab2c3f4b89608f36a" ON "collector_availability" ("collector_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_f52771d17a618f94611a890656" ON "collector_availability" ("day_of_week") `);
        await queryRunner.query(`CREATE TABLE "ratings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "job_id" uuid NOT NULL, "household_id" uuid NOT NULL, "collector_id" uuid NOT NULL, "value" smallint NOT NULL, "comment" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_77e54384258e12a34faa920196d" UNIQUE ("job_id"), CONSTRAINT "REL_77e54384258e12a34faa920196" UNIQUE ("job_id"), CONSTRAINT "PK_0f31425b073219379545ad68ed9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_77e54384258e12a34faa920196" ON "ratings" ("job_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_1486a1ed5d83f4d729b3caa25d" ON "ratings" ("collector_id") `);
        await queryRunner.query(`CREATE TYPE "public"."notifications_channel_enum" AS ENUM('PUSH', 'SMS', 'IN_APP')`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_status_enum" AS ENUM('PENDING', 'SENT', 'FAILED', 'READ')`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "type" character varying(50) NOT NULL, "title" character varying(200) NOT NULL, "body" text NOT NULL, "data" jsonb NOT NULL DEFAULT '{}', "channel" "public"."notifications_channel_enum" NOT NULL, "status" "public"."notifications_status_enum" NOT NULL DEFAULT 'PENDING', "sent_at" TIMESTAMP WITH TIME ZONE, "read_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9a8a82462cab47c73d25f49261" ON "notifications" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_92f5d3a7779be163cbea7916c6" ON "notifications" ("status") `);
        await queryRunner.query(`CREATE TABLE "proofs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "job_id" uuid NOT NULL, "image_url" character varying(500) NOT NULL, "thumbnail_url" character varying(500), "collector_lat" numeric(10,8), "collector_lng" numeric(11,8), "uploaded_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_149b2e9f43ad79b6fe6f18a941f" UNIQUE ("job_id"), CONSTRAINT "REL_149b2e9f43ad79b6fe6f18a941" UNIQUE ("job_id"), CONSTRAINT "PK_06490e8196a39d54b57090a634c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_149b2e9f43ad79b6fe6f18a941" ON "proofs" ("job_id") `);
        await queryRunner.query(`CREATE TYPE "public"."fraud_flags_type_enum" AS ENUM('FAST_COMPLETION', 'GPS_MISMATCH', 'IMAGE_REUSE', 'SUSPICIOUS_PATTERN', 'DUPLICATE_REQUEST')`);
        await queryRunner.query(`CREATE TYPE "public"."fraud_flags_severity_enum" AS ENUM('LOW', 'MEDIUM', 'HIGH')`);
        await queryRunner.query(`CREATE TYPE "public"."fraud_flags_status_enum" AS ENUM('OPEN', 'REVIEWED', 'DISMISSED', 'CONFIRMED')`);
        await queryRunner.query(`CREATE TABLE "fraud_flags" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "job_id" uuid NOT NULL, "collector_id" uuid NOT NULL, "type" "public"."fraud_flags_type_enum" NOT NULL, "severity" "public"."fraud_flags_severity_enum" NOT NULL, "details" jsonb NOT NULL DEFAULT '{}', "status" "public"."fraud_flags_status_enum" NOT NULL DEFAULT 'OPEN', "reviewed_by" uuid, "review_notes" text, "reviewed_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_00fccadb758d1624e0831fe026a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9f6800f125ccea1846f653cb38" ON "fraud_flags" ("job_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_4cebb34fc4caa03a209dedebad" ON "fraud_flags" ("collector_id") `);
        await queryRunner.query(`CREATE TYPE "public"."files_file_type_enum" AS ENUM('PROOF', 'AVATAR', 'OTHER')`);
        await queryRunner.query(`CREATE TABLE "files" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "file_key" uuid NOT NULL, "url" character varying(1000) NOT NULL, "delete_url" character varying(1000), "uploaded_by" uuid NOT NULL, "file_type" "public"."files_file_type_enum" NOT NULL DEFAULT 'OTHER', "is_used" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_9a02ba48ab7537f785bdc47b7b6" UNIQUE ("file_key"), CONSTRAINT "PK_6c16b9093a142e0e7613b04a3d9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_9a02ba48ab7537f785bdc47b7b" ON "files" ("file_key") `);
        await queryRunner.query(`CREATE INDEX "IDX_63c92c51cd7fd95c2d79d709b6" ON "files" ("uploaded_by") `);
        await queryRunner.query(`CREATE TYPE "public"."earnings_status_enum" AS ENUM('PENDING', 'CONFIRMED', 'PAID')`);
        await queryRunner.query(`CREATE TABLE "earnings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "job_id" uuid NOT NULL, "collector_id" uuid NOT NULL, "base_amount" numeric(10,2) NOT NULL, "distance_amount" numeric(10,2) NOT NULL DEFAULT '0', "surge_multiplier" numeric(3,2) NOT NULL DEFAULT '1', "total_amount" numeric(10,2) NOT NULL, "status" "public"."earnings_status_enum" NOT NULL DEFAULT 'PENDING', "confirmed_at" TIMESTAMP WITH TIME ZONE, "paid_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_e4febb6bc033b50c54fe528ecdf" UNIQUE ("job_id"), CONSTRAINT "REL_e4febb6bc033b50c54fe528ecd" UNIQUE ("job_id"), CONSTRAINT "PK_32821f77c2546a1d53f674fe83f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6406cc998fc9703cbf66c38717" ON "earnings" ("collector_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_12d83992076c628f4d4dfce38b" ON "earnings" ("status") `);
        await queryRunner.query(`CREATE TYPE "public"."disputes_status_enum" AS ENUM('OPEN', 'RESOLVED_ACCEPTED', 'RESOLVED_REJECTED')`);
        await queryRunner.query(`CREATE TABLE "disputes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "job_id" uuid NOT NULL, "household_id" uuid NOT NULL, "reason" text NOT NULL, "status" "public"."disputes_status_enum" NOT NULL DEFAULT 'OPEN', "admin_notes" text, "resolved_by" uuid, "resolved_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_8b8bfb0d30ce224ca34787db375" UNIQUE ("job_id"), CONSTRAINT "REL_8b8bfb0d30ce224ca34787db37" UNIQUE ("job_id"), CONSTRAINT "PK_3c97580d01c1a4b0b345c42a107" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8b8bfb0d30ce224ca34787db37" ON "disputes" ("job_id") `);
        await queryRunner.query(`CREATE TABLE "system_config" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "key" character varying(100) NOT NULL, "value" character varying(500) NOT NULL, "data_type" character varying(20) NOT NULL DEFAULT 'string', "category" character varying(50) NOT NULL, "description" text, "is_feature_flag" boolean NOT NULL DEFAULT false, "updated_by" uuid, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), CONSTRAINT "UQ_eedd3cd0f227c7fb5eff2204e93" UNIQUE ("key"), CONSTRAINT "PK_db4e70ac0d27e588176e9bb44a0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_eedd3cd0f227c7fb5eff2204e9" ON "system_config" ("key") `);
        await queryRunner.query(`CREATE INDEX "IDX_3b57ad4b9cff09d96a08d117bb" ON "system_config" ("category") `);
        await queryRunner.query(`ALTER TABLE "jobs" ADD CONSTRAINT "FK_b51d60266d53e1df466549d98dc" FOREIGN KEY ("household_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "jobs" ADD CONSTRAINT "FK_d189aac72bc65e3550769bb734d" FOREIGN KEY ("collector_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "location_updates" ADD CONSTRAINT "FK_78d25ae7727e1b82de588b77092" FOREIGN KEY ("job_id") REFERENCES "jobs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "location_updates" ADD CONSTRAINT "FK_66690e907180545dbed68e228c1" FOREIGN KEY ("collector_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "collector_availability" ADD CONSTRAINT "FK_06a030107ab2c3f4b89608f36a0" FOREIGN KEY ("collector_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ratings" ADD CONSTRAINT "FK_77e54384258e12a34faa920196d" FOREIGN KEY ("job_id") REFERENCES "jobs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ratings" ADD CONSTRAINT "FK_6ba959ce3adc3cb9017581c37b3" FOREIGN KEY ("household_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ratings" ADD CONSTRAINT "FK_1486a1ed5d83f4d729b3caa25d8" FOREIGN KEY ("collector_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_9a8a82462cab47c73d25f49261f" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "proofs" ADD CONSTRAINT "FK_149b2e9f43ad79b6fe6f18a941f" FOREIGN KEY ("job_id") REFERENCES "jobs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fraud_flags" ADD CONSTRAINT "FK_9f6800f125ccea1846f653cb389" FOREIGN KEY ("job_id") REFERENCES "jobs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fraud_flags" ADD CONSTRAINT "FK_4cebb34fc4caa03a209dedebada" FOREIGN KEY ("collector_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fraud_flags" ADD CONSTRAINT "FK_5d1271c5b2dff7f49d1ee0e9378" FOREIGN KEY ("reviewed_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "files" ADD CONSTRAINT "FK_63c92c51cd7fd95c2d79d709b61" FOREIGN KEY ("uploaded_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "earnings" ADD CONSTRAINT "FK_e4febb6bc033b50c54fe528ecdf" FOREIGN KEY ("job_id") REFERENCES "jobs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "earnings" ADD CONSTRAINT "FK_6406cc998fc9703cbf66c387176" FOREIGN KEY ("collector_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "disputes" ADD CONSTRAINT "FK_8b8bfb0d30ce224ca34787db375" FOREIGN KEY ("job_id") REFERENCES "jobs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "disputes" ADD CONSTRAINT "FK_22fcbba7a6bd9a29b910469fc2f" FOREIGN KEY ("household_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "disputes" ADD CONSTRAINT "FK_573e2d4b2acb74b7f74a4d4735a" FOREIGN KEY ("resolved_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "disputes" DROP CONSTRAINT "FK_573e2d4b2acb74b7f74a4d4735a"`);
        await queryRunner.query(`ALTER TABLE "disputes" DROP CONSTRAINT "FK_22fcbba7a6bd9a29b910469fc2f"`);
        await queryRunner.query(`ALTER TABLE "disputes" DROP CONSTRAINT "FK_8b8bfb0d30ce224ca34787db375"`);
        await queryRunner.query(`ALTER TABLE "earnings" DROP CONSTRAINT "FK_6406cc998fc9703cbf66c387176"`);
        await queryRunner.query(`ALTER TABLE "earnings" DROP CONSTRAINT "FK_e4febb6bc033b50c54fe528ecdf"`);
        await queryRunner.query(`ALTER TABLE "files" DROP CONSTRAINT "FK_63c92c51cd7fd95c2d79d709b61"`);
        await queryRunner.query(`ALTER TABLE "fraud_flags" DROP CONSTRAINT "FK_5d1271c5b2dff7f49d1ee0e9378"`);
        await queryRunner.query(`ALTER TABLE "fraud_flags" DROP CONSTRAINT "FK_4cebb34fc4caa03a209dedebada"`);
        await queryRunner.query(`ALTER TABLE "fraud_flags" DROP CONSTRAINT "FK_9f6800f125ccea1846f653cb389"`);
        await queryRunner.query(`ALTER TABLE "proofs" DROP CONSTRAINT "FK_149b2e9f43ad79b6fe6f18a941f"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_9a8a82462cab47c73d25f49261f"`);
        await queryRunner.query(`ALTER TABLE "ratings" DROP CONSTRAINT "FK_1486a1ed5d83f4d729b3caa25d8"`);
        await queryRunner.query(`ALTER TABLE "ratings" DROP CONSTRAINT "FK_6ba959ce3adc3cb9017581c37b3"`);
        await queryRunner.query(`ALTER TABLE "ratings" DROP CONSTRAINT "FK_77e54384258e12a34faa920196d"`);
        await queryRunner.query(`ALTER TABLE "collector_availability" DROP CONSTRAINT "FK_06a030107ab2c3f4b89608f36a0"`);
        await queryRunner.query(`ALTER TABLE "location_updates" DROP CONSTRAINT "FK_66690e907180545dbed68e228c1"`);
        await queryRunner.query(`ALTER TABLE "location_updates" DROP CONSTRAINT "FK_78d25ae7727e1b82de588b77092"`);
        await queryRunner.query(`ALTER TABLE "jobs" DROP CONSTRAINT "FK_d189aac72bc65e3550769bb734d"`);
        await queryRunner.query(`ALTER TABLE "jobs" DROP CONSTRAINT "FK_b51d60266d53e1df466549d98dc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3b57ad4b9cff09d96a08d117bb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_eedd3cd0f227c7fb5eff2204e9"`);
        await queryRunner.query(`DROP TABLE "system_config"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8b8bfb0d30ce224ca34787db37"`);
        await queryRunner.query(`DROP TABLE "disputes"`);
        await queryRunner.query(`DROP TYPE "public"."disputes_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_12d83992076c628f4d4dfce38b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6406cc998fc9703cbf66c38717"`);
        await queryRunner.query(`DROP TABLE "earnings"`);
        await queryRunner.query(`DROP TYPE "public"."earnings_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_63c92c51cd7fd95c2d79d709b6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9a02ba48ab7537f785bdc47b7b"`);
        await queryRunner.query(`DROP TABLE "files"`);
        await queryRunner.query(`DROP TYPE "public"."files_file_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4cebb34fc4caa03a209dedebad"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9f6800f125ccea1846f653cb38"`);
        await queryRunner.query(`DROP TABLE "fraud_flags"`);
        await queryRunner.query(`DROP TYPE "public"."fraud_flags_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."fraud_flags_severity_enum"`);
        await queryRunner.query(`DROP TYPE "public"."fraud_flags_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_149b2e9f43ad79b6fe6f18a941"`);
        await queryRunner.query(`DROP TABLE "proofs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_92f5d3a7779be163cbea7916c6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9a8a82462cab47c73d25f49261"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_channel_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1486a1ed5d83f4d729b3caa25d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_77e54384258e12a34faa920196"`);
        await queryRunner.query(`DROP TABLE "ratings"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f52771d17a618f94611a890656"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_06a030107ab2c3f4b89608f36a"`);
        await queryRunner.query(`DROP TABLE "collector_availability"`);
        await queryRunner.query(`DROP TYPE "public"."collector_availability_day_of_week_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_78d25ae7727e1b82de588b7709"`);
        await queryRunner.query(`DROP TABLE "location_updates"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a0c30e3eb9649fe7fbcd336a63"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d189aac72bc65e3550769bb734"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b51d60266d53e1df466549d98d"`);
        await queryRunner.query(`DROP TABLE "jobs"`);
        await queryRunner.query(`DROP TYPE "public"."jobs_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ace513fa30d485cfd25c11a9e4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a000cca60bcf04454e72769949"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
    }

}
